from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 788)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLineEdit(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(350, 10, 81, 51))
        self.logo.setObjectName("logo")
        self.namer_estro = QtWidgets.QLineEdit(self.centralwidget)
        self.namer_estro.setGeometry(QtCore.QRect(50, 10, 261, 51))
        self.namer_estro.setObjectName("namer_estro")
        self.address = QtWidgets.QLineEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(80, 80, 281, 61))
        self.address.setObjectName("address")
        self.gstin = QtWidgets.QLineEdit(self.centralwidget)
        self.gstin.setGeometry(QtCore.QRect(90, 160, 231, 20))
        self.gstin.setObjectName("gstin")
        self.table_no = QtWidgets.QLineEdit(self.centralwidget)
        self.table_no.setGeometry(QtCore.QRect(30, 230, 61, 20))
        self.table_no.setObjectName("table_no")
        self.bil_no = QtWidgets.QLineEdit(self.centralwidget)
        self.bil_no.setGeometry(QtCore.QRect(290, 230, 113, 20))
        self.bil_no.setObjectName("bil_no")
        self.cashier_id = QtWidgets.QLineEdit(self.centralwidget)
        self.cashier_id.setGeometry(QtCore.QRect(30, 260, 91, 20))
        self.cashier_id.setObjectName("cashier_id")
        self.date_time = QtWidgets.QLineEdit(self.centralwidget)
        self.date_time.setGeometry(QtCore.QRect(290, 260, 113, 20))
        self.date_time.setObjectName("date_time")
        self.cust_name = QtWidgets.QLineEdit(self.centralwidget)
        self.cust_name.setGeometry(QtCore.QRect(30, 290, 113, 20))
        self.cust_name.setObjectName("cust_name")
        self.cust_no = QtWidgets.QLineEdit(self.centralwidget)
        self.cust_no.setGeometry(QtCore.QRect(290, 290, 113, 20))
        self.cust_no.setObjectName("cust_no")
        self.dinein_takeaway = QtWidgets.QLineEdit(self.centralwidget)
        self.dinein_takeaway.setGeometry(QtCore.QRect(40, 320, 361, 20))
        self.dinein_takeaway.setObjectName("dinein_takeaway")
        self.total_amt = QtWidgets.QLineEdit(self.centralwidget)
        self.total_amt.setGeometry(QtCore.QRect(310, 530, 113, 20))
        self.total_amt.setObjectName("total_amt")
        self.cgst = QtWidgets.QLineEdit(self.centralwidget)
        self.cgst.setGeometry(QtCore.QRect(310, 560, 113, 20))
        self.cgst.setObjectName("cgst")
        self.sgst = QtWidgets.QLineEdit(self.centralwidget)
        self.sgst.setGeometry(QtCore.QRect(310, 590, 113, 20))
        self.sgst.setObjectName("sgst")
        self.discount = QtWidgets.QLineEdit(self.centralwidget)
        self.discount.setGeometry(QtCore.QRect(310, 620, 113, 20))
        self.discount.setObjectName("discount")
        self.bill_amt = QtWidgets.QLineEdit(self.centralwidget)
        self.bill_amt.setGeometry(QtCore.QRect(310, 650, 113, 20))
        self.bill_amt.setObjectName("bill_amt")
        self.ty_va = QtWidgets.QLineEdit(self.centralwidget)
        self.ty_va.setGeometry(QtCore.QRect(60, 690, 331, 51))
        self.ty_va.setObjectName("ty_va")
        self.fssai = QtWidgets.QLineEdit(self.centralwidget)
        self.fssai.setGeometry(QtCore.QRect(90, 190, 231, 20))
        self.fssai.setObjectName("fssai")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 350, 411, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "     LOGO"))
        self.namer_estro.setText(_translate("MainWindow", "                            NAME(RESTRO)"))
        self.address.setText(_translate("MainWindow", "                   ADDRESS"))
        self.gstin.setText(_translate("MainWindow", "GSTIN"))
        self.table_no.setText(_translate("MainWindow", "table no."))
        self.bil_no.setText(_translate("MainWindow", "bill no."))
        self.cashier_id.setText(_translate("MainWindow", "cashier id"))
        self.date_time.setText(_translate("MainWindow", "date/time"))
        self.cust_name.setText(_translate("MainWindow", "cust. name "))
        self.cust_no.setText(_translate("MainWindow", "cust. no."))
        self.dinein_takeaway.setText(_translate("MainWindow", "               DINE_IN/TAKE AWAY"))
        self.total_amt.setText(_translate("MainWindow", "TOTAL AMT"))
        self.cgst.setText(_translate("MainWindow", "ADD CGST 2.5%"))
        self.sgst.setText(_translate("MainWindow", "ADD SGST 2.5%"))
        self.discount.setText(_translate("MainWindow", "DSICOUNT"))
        self.bill_amt.setText(_translate("MainWindow", "TOTAL BILL AMOUNT"))
        self.ty_va.setText(_translate("MainWindow", "THANK YOU , VISIT AGAIN"))
        self.fssai.setText(_translate("MainWindow", "FSSAI"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "item name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "qty"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "rate"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "amt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
